BIGMVC_project-master/BIGMVC_project/Models/Department.cs
using System;
using System.Collections.Generic;

namespace BIGMVC_project.Models;

public partial class Department
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    public virtual ICollection<Manager> Managers { get; set; } = new List<Manager>();
}

BIGMVC_project-master/BIGMVC_project/Models/Employee.cs
using System;
using System.Collections.Generic;

namespace BIGMVC_project.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Email { get; set; }

    public string? PasswordHash { get; set; }

    public string? ImagePath { get; set; }

    public string? Address { get; set; }

    public string? Position { get; set; }

    public int? ManagerId { get; set; }

    public int? DepartmentId { get; set; }

    public virtual ICollection<Attendance> Attendances { get; set; } = new List<Attendance>();

    public virtual Department? Department { get; set; }

    public virtual ICollection<Evaluation> Evaluations { get; set; } = new List<Evaluation>();

    public virtual ICollection<LeaveRequest> LeaveRequests { get; set; } = new List<LeaveRequest>();

    public virtual Manager? Manager { get; set; }

    public virtual ICollection<Mission> Missions { get; set; } = new List<Mission>();
}

BIGMVC_project-master/BIGMVC_project/Models/Evaluation.cs
using System;
using System.Collections.Generic;

namespace BIGMVC_project.Models;

public partial class Evaluation
{
    public int Id { get; set; }

    public int EmployeeId { get; set; }

    public int ManagerId { get; set; }

    public string? EvaluationsStatusEnum { get; set; }

    public string? Comments { get; set; }

    public DateOnly? DateEvaluated { get; set; }

    public virtual Employee Employee { get; set; } = null!;

    public virtual Manager Manager { get; set; } = null!;
}

BIGMVC_project-master/BIGMVC_project/Models/Feedback.cs
using System;
using System.Collections.Generic;

namespace BIGMVC_project.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Email { get; set; }

    public string? Message { get; set; }

    public DateTime? SubmittedAt { get; set; }

    public string? ReplyMessage { get; set; }
}

BIGMVC_project-master/BIGMVC_project/Models/Hr.cs
using System;
using System.Collections.Generic;

namespace BIGMVC_project.Models;

public partial class Hr
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Email { get; set; }

    public string? PasswordHash { get; set; }

    public string? Image { get; set; }
}

BIGMVC_project-master/BIGMVC_project/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BIGMVC_project.Models;

namespace BIGMVC_project.Controllers
{
	public class EvaluationsController : Controller
	{
		private readonly MyDbContext _context;

		public EvaluationsController(MyDbContext context)
		{
			_context = context;
		}

		// GET: Evaluations
		public async Task<IActionResult> Index()
		{
			var myDbContext = _context.Evaluations.Include(e => e.Employee).Include(e => e.Manager);
			return View(await myDbContext.ToListAsync());
		}

		// GET: Evaluations/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var evaluation = await _context.Evaluations
				.Include(e => e.Employee)
				.Include(e => e.Manager)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (evaluation == null)
			{
				return NotFound();
			}

			return View(evaluation);
		}

		// GET: Evaluations/Create
		public IActionResult Create()
		{
			ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id");
			ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Id");
			return View();
		}

		// POST: Evaluations/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,EmployeeId,ManagerId,EvaluationsStatusEnum,Comments,DateEvaluated")] Evaluation evaluation)
		{
			if (ModelState.IsValid)
			{
				_context.Add(evaluation);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", evaluation.EmployeeId);
			ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Id", evaluation.ManagerId);
			return View(evaluation);
		}

		// GET: Evaluations/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var evaluation = await _context.Evaluations.FindAsync(id);
			if (evaluation == null)
			{
				return NotFound();
			}
			ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", evaluation.EmployeeId);
			ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Id", evaluation.ManagerId);
			return View(evaluation);
		}

		// POST: Evaluations/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,EmployeeId,ManagerId,EvaluationsStatusEnum,Comments,DateEvaluated")] Evaluation evaluation)
		{
			if (id != evaluation.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(evaluation);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!EvaluationExists(evaluation.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			ViewData["EmployeeId"] = new SelectList(_context.Employees, "Id", "Id", evaluation.EmployeeId);
			ViewData["ManagerId"] = new SelectList(_context.Managers, "Id", "Id", evaluation.ManagerId);
			return View(evaluation);
		}

		// GET: Evaluations/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var evaluation = await _context.Evaluations
				.Include(e => e.Employee)
				.Include(e => e.Manager)
				.FirstOrDefaultAsync(m => m.Id == id);
			if (evaluation == null)
			{
				return NotFound();
			}

			return View(evaluation);
		}

		// POST: Evaluations/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var evaluation = await _context.Evaluations.FindAsync(id);
			if (evaluation != null)
			{
				_context.Evaluations.Remove(evaluation);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool EvaluationExists(int id)
		{
			return _context.Evaluations.Any(e => e.Id == id);
		}
	}
}

BIGMVC_project-master/BIGMVC_project/Controllers/HrsController.cs
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using BIGMVC_project.Models;
using System.Xml.Linq;
//using HR_Management.Data;
//using HR_Management.Model;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HR_Management.Controllers
{
	public class HrsController : Controller
	{
		private readonly MyDbContext _context;

		public HrsController(MyDbContext context)
		{
			_context = context;
		}
		public IActionResult Dashboard()
		{

			var totalHR = _context.Hrs.Count();
			var totalEmployees = _context.Employees.Count();
			var totalManagers = _context.Managers.Count();
			var totalDepartments = _context.Departments.Count();
			var tasks = _context.Missions.Include(m => m.Employee).ToList();

			ViewBag.Tasks = tasks;
			ViewBag.TotalTasks = tasks.Count();
			ViewBag.TotalHR = totalHR;
			ViewBag.TotalEmployees = totalEmployees;
			ViewBag.TotalManagers = totalManagers;
			ViewBag.TotalDepartments = totalDepartments;

			var departmentEmployeeCount = _context.Employees
				.GroupBy(e => e.Department.Name)
				.Select(group => new
				{
					DepartmentName = group.Key,
					EmployeeCount = group.Count()
				})
				.ToList();

			ViewBag.DepartmentEmployeeCount = departmentEmployeeCount;

			return View();
		}




		public IActionResult LeaveRequests()
		{
			var allLeaveRequests = _context.LeaveRequests.ToList();
			return View(allLeaveRequests);
		}

		public IActionResult Feedback()
		{
			var feedbackList = _context.Feedbacks.ToList();
			return View(feedbackList);
		}


		[HttpPost]
		public async Task<IActionResult> SubmitFeedback(Feedback feedback)
		{
			if (ModelState.IsValid)
			{
				feedback.SubmittedAt = DateTime.Now;
				_context.Feedbacks.Add(feedback);
				await _context.SaveChangesAsync();
				TempData["Success"] = "Success!";
				return RedirectToAction("Feedback");
			}

			return View("Feedback", feedback);
		}


		[HttpPost]
		public async Task<IActionResult> DeleteFeedback(int id)
		{
			var feedback = await _context.Feedbacks.FindAsync(id);
			if (feedback != null)
			{
				_context.Feedbacks.Remove(feedback);
				await _context.SaveChangesAsync();
			}

			return RedirectToAction("Feedback");
		}


		[HttpPost]
		public async Task<IActionResult> ReplyToFeedback(int id, string reply)
		{
			var feedback = await _context.Feedbacks.FindAsync(id);
			if (feedback == null)
			{
				return NotFound();
			}

			feedback.ReplyMessage = reply;
			_context.Feedbacks.Update(feedback);
			await _context.SaveChangesAsync();

			TempData["Success"] = "Success!";
			return RedirectToAction("Feedback");
		}


		//public IActionResult ContactUs()
		//{
		//    return View(new Feedback());
		//}


		[HttpPost]
		public IActionResult SendFeedback(Feedback feedback)
		{
			if (ModelState.IsValid)
			{
				feedback.SubmittedAt = DateTime.Now;
				_context.Feedbacks.Add(feedback);
				_context.SaveChanges();
				return RedirectToAction("ContactUs");
			}

			return View("ContactUs", feedback);
		}


		public IActionResult AddManager()
		{
			var departments = _context.Departments.ToList(); // assuming you're using Entity Framework
			ViewBag.Departments = departments;
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> AddManager(Manager model, IFormFile profilePicture)
		{
			// Check if email is already taken
			if (_context.Managers.Any(m => m.Email == model.Email))
			{
				ModelState.AddModelError("Email", "This email is already in use.");
				return View(model);
			}

			// Check if the model is valid
			if (!ModelState.IsValid)
			{
				return View(model); // Return the view with validation errors if the model is invalid
			}

			// Handle profile picture upload
			if (profilePicture != null && profilePicture.Length > 0)
			{
				var allowedExtensions = new[] { ".jpg", ".jpeg", ".png" };
				var fileExtension = Path.GetExtension(profilePicture.FileName).ToLower();
				if (!allowedExtensions.Contains(fileExtension))
				{
					ModelState.AddModelError("ProfilePicture", "Invalid image format. Only .jpg, .jpeg, and .png are allowed.");
					return View(model);
				}

				// Clean the filename to avoid invalid characters
				var fileName = Path.GetFileNameWithoutExtension(profilePicture.FileName);
				var cleanedFileName = Path.Combine(fileName + fileExtension); // Add extension back
				var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", "managers", cleanedFileName);
				var directoryPath = Path.GetDirectoryName(filePath);

				if (!Directory.Exists(directoryPath))
				{
					Directory.CreateDirectory(directoryPath);
				}

				using (var stream = new FileStream(filePath, FileMode.Create))
				{
					await profilePicture.CopyToAsync(stream);
				}

				model.Image = cleanedFileName;
			}

			// Add the manager to the context
			_context.Managers.Add(model);
			await _context.SaveChangesAsync();

			// Redirect to a relevant action (for example, the details page of the new manager)
			return RedirectToAction("ManagerDetails", new { id = model.Id });
		}

		// GET: Hrs/ManagerDetails/5
		[HttpGet("manager/details/{id}")]
		public IActionResult ManagerDetails(int id)
		{
			var manager = _context.Managers
				.Include(m => m.Department)
				.FirstOrDefault(m => m.Id == id);

			if (manager == null)
			{
				return NotFound();
			}

			return RedirectToAction("Manager");
		}
		public IActionResult ExportLeaveRequestsToPDF()
		{
			var leaveRequests = _context.LeaveRequests.ToList();

			var pdfStream = new MemoryStream();

			var document = new Document(PageSize.A4);
			var writer = PdfWriter.GetInstance(document, pdfStream);

			document.Open();

			var font = FontFactory.GetFont("Arial", 20, Font.BOLD);
			Paragraph title = new Paragraph("Leave Requests", font)
			{
				Alignment = Element.ALIGN_CENTER
			};

			title.SpacingAfter = 20f;

			document.Add(title);

			document.Add(new Paragraph(" "));

			var table = new PdfPTable(5) { WidthPercentage = 100 };
			table.SpacingBefore = 20f;

			table.AddCell("Employee ID");
			table.AddCell("Start Date");
			table.AddCell("End Date");
			table.AddCell("Reason");
			table.AddCell("Status");

			foreach (var request in leaveRequests)
			{
				table.AddCell(request.EmployeeId.ToString());
				table.AddCell(request.StartDate.ToShortDateString());
				table.AddCell(request.EndDate.ToShortDateString());
				table.AddCell(request.Reason);
				table.AddCell(request.LeaveRequestsStatusEnum);
			}

			document.Add(table);

			document.Close();

			return File(pdfStream.ToArray(), "application/pdf", "LeaveRequests.pdf");
		}

		public IActionResult DepartmentService()
		{
			return View();
		}
		//////////////////////////////////////
		/////////////////////////////////////////////
		/////////////////////////////////////////////
		///// GET: Hrs
		public async Task<IActionResult> Index()
		{
			return View(await _context.Hrs.ToListAsync());
		}

		// GET: Hrs/Details/5
		public async Task<IActionResult> HRDetails(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var hr = await _context.Hrs
				.FirstOrDefaultAsync(m => m.Id == id);
			if (hr == null)
			{
				return NotFound();
			}

			return View(hr);
		}

		// GET: Hrs/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Hrs/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Name,Email,PasswordHash,Image")] Hr hr)
		{
			if (ModelState.IsValid)
			{
				_context.Add(hr);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(hr);
		}

		// GET: Hrs/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var hr = await _context.Hrs.FindAsync(id);
			if (hr == null)
			{
				return NotFound();
			}
			return View(hr);
		}

		// POST: Hrs/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,PasswordHash,Image")] Hr hr)
		{
			if (id != hr.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(hr);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!HrExists(hr.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(hr);
		}

		// GET: Hrs/Delete/5
		// GET: Hrs/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var hr = await _context.Hrs
				.FirstOrDefaultAsync(m => m.Id == id);
			if (hr == null)
			{
				return NotFound();
			}

			return View(hr);
		}

		// GET: Hrs/Create
		public IActionResult Createe()
		{
			return View(); // This will display the Create.cshtml form
		}

		// POST: Hrs/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Createe([Bind("Name,Email,PasswordHash,Image")] Hr hr)
		{
			if (ModelState.IsValid)
			{
				_context.Add(hr);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index)); // Redirect to HR list after creation
			}
			return View(hr); // Re-display form with validation errors
		}

		// POST: Hrs/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var hr = await _context.Hrs.FindAsync(id);
			if (hr != null)
			{
				_context.Hrs.Remove(hr);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool HrExists(int id)
		{
			return _context.Hrs.Any(e => e.Id == id);
		}

		// Export HR data to PDF
		public IActionResult ExportHRToPDF()
		{
			var HR = _context.Hrs.ToList();

BIGMVC_project-master/BIGMVC_project/Views/Hrs/Createe.cshtml
@model BIGMVC_project.Models.Hr

@{
    ViewData["Title"] = "Create HR";
}

<h1>Create HR</h1>

<hr />

<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PasswordHash" class="control-label"></label>
        <input asp-for="PasswordHash" class="form-control" />
        <span asp-validation-for="PasswordHash" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image" class="control-label"></label>
        <input type="file" name="Image" class="form-control" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

BIGMVC_project-master/BIGMVC_project/Views/Hrs/Delete.cshtml
@model BIGMVC_project.Models.Hr

@{
    ViewData["Title"] = "DeleteConfirmed";
}

<h1>DeleteConfirmed</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hr</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BIGMVC_project-master/BIGMVC_project/Views/Hrs/Department.cshtml
@{
    ViewData["Title"] = "Department";
}
@model IEnumerable<Department>
<h1 style="color:black;">Department</h1>
<hr/>
<a asp-action="DepartmentCreate" class="btn btn-primary">Create New</a>
<a asp-action="ManagerToPDF" asp-controller="Hrs" class="btn btn-primary">Download PDF</a>
<div class="card-container">
	@foreach (var item in Model)
	{
		<div class="card" onclick="toggleCard(this)" style="border: 1px solid #ddd; border-radius: 8px; margin: 10px; padding: 15px; cursor: pointer; transition: box-shadow 0.3s ease;">
			<div class="card-header" style="font-weight: bold; font-size: 18px;">
				@Html.DisplayFor(modelItem => item.Name)
			</div>
			<div class="card-details" style="display: none; margin-top: 10px;">
				<p><strong>Description:</strong> @Html.DisplayFor(modelItem => item.Description)</p>
				<a asp-action="DetailsDepartment" asp-route-id="@item.Id" class="btn btn-info">Details</a>
			</div>
		</div>
	}
</div>
<script>
	function toggleCard(card) {
		card.classList.toggle('expanded');
		let details = card.querySelector('.card-details');
		if (card.classList.contains('expanded')) {
			details.style.display = 'block';
		} else {
			details.style.display = 'none';
		}
	}
</script>

BIGMVC_project-master/BIGMVC_project/Views/Hrs/Edit.cshtml
@model BIGMVC_project.Models.Hr

@{
    ViewData["Title"] = "Edit HR";
}

<h1>Edit HR</h1>

<hr />

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PasswordHash" class="control-label"></label>
        <input asp-for="PasswordHash" class="form-control" />
        <span asp-validation-for="PasswordHash" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Image" class="control-label"></label>
        <input type="file" name="Image" class="form-control" />
        <span asp-validation-for="Image" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Save</button>
        <a asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

BIGMVC_project-master/BIGMVC_project/Views/Hrs/Index.cshtml
@model IEnumerable<BIGMVC_project.Models.Hr>

@{
    ViewData["Title"] = "HR Team";
}

<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1 class="display-4 text-primary">HR Team Management</h1>
        <div>
            <a asp-action="ExportHRToPDF" asp-controller="Hrs" class="btn btn-outline-primary me-2">
                <i class="bi bi-file-earmark-pdf"></i> Export PDF
            </a>
            <a asp-action="Createe" class="btn btn-success">
                <i class="bi bi-person-plus"></i> Add New HR
            </a>
        </div>
    </div>

    <div class="card shadow-sm">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-hover table-striped mb-0">
                    <thead class="table-dark">
                        <tr>
                            <th scope="col" class="text-nowrap"># ID</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col" class="text-end">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Email</td>
                                <td class="text-end">
                                    <div class="btn-group" role="group">
                                        <a asp-action="HRDetails" asp-route-id="@item.Id"
                                           class="btn btn-sm btn-outline-info me-2">
                                            <i class="bi bi-eye"></i> Details
                                        </a>
                                        <a asp-action="Edit" asp-route-id="@item.Id"
                                           class="btn btn-sm btn-outline-warning me-2">
                                            <i class="bi bi-pencil-square"></i> Edit
                                        </a>
                                        <a asp-action="Delete" asp-route-id="@item.Id"
                                           class="btn btn-sm btn-outline-danger">
                                            <i class="bi bi-trash"></i> Delete
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<style>
    .table-hover tbody tr:hover {
        background-color: #f8f9fa;
        transform: translateX(4px);
        transition: all 0.3s ease;
    }

    .table-dark {
        background-color: #2c3e50;
    }

    .card {
        border-radius: 0.5rem;
        border: none;
    }

    .btn-group .btn {
        border-radius: 0.25rem;
    }

    .bi {
        margin-right: 0.5rem;
    }
</style>

BIGMVC_project-master/BIGMVC_project/Views/Hrs/Manager.cshtml
@model IEnumerable<Manager>

<style>
    body {
        background-color: white;
    }

    .table th, .table td {
        vertical-align: middle;
        text-align: center;
    }

    .manager-image {
        width: 80px;
        height: 80px;
        border-radius: 50%;
        object-fit: cover;
    }
</style>

<h1 style="color:black;">Managers List</h1>

<hr />
<a asp-action="AddManager" class="btn btn-primary">Create New</a>
<a asp-action="ManagerToPDF" asp-controller="Hrs" class="btn btn-primary">Download PDF</a>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Image</th>
            <th>Name</th>
            <th>Email</th>
            <th>Department</th>
            <th>Actions</th> 
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item?.Id</td>
                <td>
                    @if (!string.IsNullOrEmpty(item?.Image))
                    {
                        <img src="~/images/managers/@item.Image" class="manager-image" alt="Manager Image" />
                    }
                    else
                    {
                        <p>No image available</p>
                    }
                </td>
                <td>@item?.Name</td>
                <td>@item?.Email</td>
                <td>@(item?.Department != null ? item.Department.Name : "No Department")</td>
                <td>
                    <a asp-action="ManagerEdit" asp-route-id="@item.Id" class="btn btn-warning">Edit</a>
                    <form asp-action="ManagerDelete" asp-route-id="@item.Id" method="post" onsubmit="return confirm('Are you sure?');">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>